/*
 * generated by Xtext 2.10.0
 */
package org.kulto.ui;

import com.google.inject.Injector;
import kultodsl.ui.internal.KultodslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KultoDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KultodslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KultodslActivator.getInstance().getInjector(KultodslActivator.ORG_KULTO_KULTODSL);
	}
	
}
