/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.kulto.kultoDsl.DomainChild;
import org.kulto.kultoDsl.KultoDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain Child</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DomainChildImpl extends MinimalEObjectImpl.Container implements DomainChild
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DomainChildImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KultoDslPackage.Literals.DOMAIN_CHILD;
  }

} //DomainChildImpl
