/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.kulto.kultoDsl.Domain;
import org.kulto.kultoDsl.DomainChild;
import org.kulto.kultoDsl.KultoDslPackage;
import org.kulto.kultoDsl.Popis;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.kulto.kultoDsl.impl.DomainImpl#getPopis <em>Popis</em>}</li>
 *   <li>{@link org.kulto.kultoDsl.impl.DomainImpl#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DomainImpl extends RootElementImpl implements Domain
{
  /**
   * The cached value of the '{@link #getPopis() <em>Popis</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPopis()
   * @generated
   * @ordered
   */
  protected Popis popis;

  /**
   * The cached value of the '{@link #getChildren() <em>Children</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChildren()
   * @generated
   * @ordered
   */
  protected EList<DomainChild> children;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KultoDslPackage.Literals.DOMAIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Popis getPopis()
  {
    return popis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPopis(Popis newPopis, NotificationChain msgs)
  {
    Popis oldPopis = popis;
    popis = newPopis;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KultoDslPackage.DOMAIN__POPIS, oldPopis, newPopis);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPopis(Popis newPopis)
  {
    if (newPopis != popis)
    {
      NotificationChain msgs = null;
      if (popis != null)
        msgs = ((InternalEObject)popis).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KultoDslPackage.DOMAIN__POPIS, null, msgs);
      if (newPopis != null)
        msgs = ((InternalEObject)newPopis).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KultoDslPackage.DOMAIN__POPIS, null, msgs);
      msgs = basicSetPopis(newPopis, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KultoDslPackage.DOMAIN__POPIS, newPopis, newPopis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<DomainChild> getChildren()
  {
    if (children == null)
    {
      children = new EObjectContainmentEList<DomainChild>(DomainChild.class, this, KultoDslPackage.DOMAIN__CHILDREN);
    }
    return children;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN__POPIS:
        return basicSetPopis(null, msgs);
      case KultoDslPackage.DOMAIN__CHILDREN:
        return ((InternalEList<?>)getChildren()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN__POPIS:
        return getPopis();
      case KultoDslPackage.DOMAIN__CHILDREN:
        return getChildren();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN__POPIS:
        setPopis((Popis)newValue);
        return;
      case KultoDslPackage.DOMAIN__CHILDREN:
        getChildren().clear();
        getChildren().addAll((Collection<? extends DomainChild>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN__POPIS:
        setPopis((Popis)null);
        return;
      case KultoDslPackage.DOMAIN__CHILDREN:
        getChildren().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN__POPIS:
        return popis != null;
      case KultoDslPackage.DOMAIN__CHILDREN:
        return children != null && !children.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //DomainImpl
