/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.kulto.kultoDsl.DomainType;
import org.kulto.kultoDsl.KultoDslPackage;
import org.kulto.kultoDsl.Popis;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.kulto.kultoDsl.impl.DomainTypeImpl#getPopis <em>Popis</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DomainTypeImpl extends TypeImpl implements DomainType
{
  /**
   * The cached value of the '{@link #getPopis() <em>Popis</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPopis()
   * @generated
   * @ordered
   */
  protected Popis popis;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DomainTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KultoDslPackage.Literals.DOMAIN_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Popis getPopis()
  {
    return popis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPopis(Popis newPopis, NotificationChain msgs)
  {
    Popis oldPopis = popis;
    popis = newPopis;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, KultoDslPackage.DOMAIN_TYPE__POPIS, oldPopis, newPopis);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPopis(Popis newPopis)
  {
    if (newPopis != popis)
    {
      NotificationChain msgs = null;
      if (popis != null)
        msgs = ((InternalEObject)popis).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - KultoDslPackage.DOMAIN_TYPE__POPIS, null, msgs);
      if (newPopis != null)
        msgs = ((InternalEObject)newPopis).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - KultoDslPackage.DOMAIN_TYPE__POPIS, null, msgs);
      msgs = basicSetPopis(newPopis, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, KultoDslPackage.DOMAIN_TYPE__POPIS, newPopis, newPopis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN_TYPE__POPIS:
        return basicSetPopis(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN_TYPE__POPIS:
        return getPopis();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN_TYPE__POPIS:
        setPopis((Popis)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN_TYPE__POPIS:
        setPopis((Popis)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case KultoDslPackage.DOMAIN_TYPE__POPIS:
        return popis != null;
    }
    return super.eIsSet(featureID);
  }

} //DomainTypeImpl
