/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.kulto.kultoDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class KultoDslFactoryImpl extends EFactoryImpl implements KultoDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static KultoDslFactory init()
  {
    try
    {
      KultoDslFactory theKultoDslFactory = (KultoDslFactory)EPackage.Registry.INSTANCE.getEFactory(KultoDslPackage.eNS_URI);
      if (theKultoDslFactory != null)
      {
        return theKultoDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new KultoDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public KultoDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case KultoDslPackage.KULTO_MODEL: return createKultoModel();
      case KultoDslPackage.ROOT_ELEMENT: return createRootElement();
      case KultoDslPackage.IMPORT: return createImport();
      case KultoDslPackage.TYPE: return createType();
      case KultoDslPackage.DOMAIN_TYPE: return createDomainType();
      case KultoDslPackage.PRIMITIVE: return createPrimitive();
      case KultoDslPackage.ENNUM: return createEnnum();
      case KultoDslPackage.ENNUM_LITERAL: return createEnnumLiteral();
      case KultoDslPackage.ENTITY: return createEntity();
      case KultoDslPackage.ATTRIBUTE: return createAttribute();
      case KultoDslPackage.DOMAIN_PACKAGE: return createDomainPackage();
      case KultoDslPackage.DOMAIN: return createDomain();
      case KultoDslPackage.DOMAIN_CHILD: return createDomainChild();
      case KultoDslPackage.APPLICATION: return createApplication();
      case KultoDslPackage.POPIS: return createPopis();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public KultoModel createKultoModel()
  {
    KultoModelImpl kultoModel = new KultoModelImpl();
    return kultoModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RootElement createRootElement()
  {
    RootElementImpl rootElement = new RootElementImpl();
    return rootElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainType createDomainType()
  {
    DomainTypeImpl domainType = new DomainTypeImpl();
    return domainType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Primitive createPrimitive()
  {
    PrimitiveImpl primitive = new PrimitiveImpl();
    return primitive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ennum createEnnum()
  {
    EnnumImpl ennum = new EnnumImpl();
    return ennum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnnumLiteral createEnnumLiteral()
  {
    EnnumLiteralImpl ennumLiteral = new EnnumLiteralImpl();
    return ennumLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity createEntity()
  {
    EntityImpl entity = new EntityImpl();
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainPackage createDomainPackage()
  {
    DomainPackageImpl domainPackage = new DomainPackageImpl();
    return domainPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Domain createDomain()
  {
    DomainImpl domain = new DomainImpl();
    return domain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainChild createDomainChild()
  {
    DomainChildImpl domainChild = new DomainChildImpl();
    return domainChild;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Application createApplication()
  {
    ApplicationImpl application = new ApplicationImpl();
    return application;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Popis createPopis()
  {
    PopisImpl popis = new PopisImpl();
    return popis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public KultoDslPackage getKultoDslPackage()
  {
    return (KultoDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static KultoDslPackage getPackage()
  {
    return KultoDslPackage.eINSTANCE;
  }

} //KultoDslFactoryImpl
