/**
 * generated by Xtext 2.10.0
 */
package org.kulto;

import org.kulto.KultoDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KultoDslStandaloneSetup extends KultoDslStandaloneSetupGenerated {
  public static void doSetup() {
    KultoDslStandaloneSetup _kultoDslStandaloneSetup = new KultoDslStandaloneSetup();
    _kultoDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
