/**
 * generated by Xtext 2.10.0
 */
package org.kulto;

import org.eclipse.xtext.formatting.IFormatter;
import org.kulto.AbstractKultoDslRuntimeModule;
import org.kulto.formatting.KultoDslFormatter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class KultoDslRuntimeModule extends AbstractKultoDslRuntimeModule {
  @Override
  public Class<? extends IFormatter> bindIFormatter() {
    return KultoDslFormatter.class;
  }
}
