/*
 * generated by Xtext 2.10.0
 */
package org.kulto.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKultoDslScopeProvider extends DelegatingScopeProvider {
}
