/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.kulto.kultoDsl.Application#getDomains <em>Domains</em>}</li>
 * </ul>
 *
 * @see org.kulto.kultoDsl.KultoDslPackage#getApplication()
 * @model
 * @generated
 */
public interface Application extends RootElement
{
  /**
   * Returns the value of the '<em><b>Domains</b></em>' reference list.
   * The list contents are of type {@link org.kulto.kultoDsl.Domain}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Domains</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domains</em>' reference list.
   * @see org.kulto.kultoDsl.KultoDslPackage#getApplication_Domains()
   * @model
   * @generated
   */
  EList<Domain> getDomains();

} // Application
