/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Child</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.kulto.kultoDsl.KultoDslPackage#getDomainChild()
 * @model
 * @generated
 */
public interface DomainChild extends EObject
{
} // DomainChild
