/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.kulto.kultoDsl.DomainType#getPopis <em>Popis</em>}</li>
 * </ul>
 *
 * @see org.kulto.kultoDsl.KultoDslPackage#getDomainType()
 * @model
 * @generated
 */
public interface DomainType extends Type, DomainChild
{
  /**
   * Returns the value of the '<em><b>Popis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Popis</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Popis</em>' containment reference.
   * @see #setPopis(Popis)
   * @see org.kulto.kultoDsl.KultoDslPackage#getDomainType_Popis()
   * @model containment="true"
   * @generated
   */
  Popis getPopis();

  /**
   * Sets the value of the '{@link org.kulto.kultoDsl.DomainType#getPopis <em>Popis</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Popis</em>' containment reference.
   * @see #getPopis()
   * @generated
   */
  void setPopis(Popis value);

} // DomainType
