/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ennum Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.kulto.kultoDsl.EnnumLiteral#getName <em>Name</em>}</li>
 *   <li>{@link org.kulto.kultoDsl.EnnumLiteral#getPopis <em>Popis</em>}</li>
 * </ul>
 *
 * @see org.kulto.kultoDsl.KultoDslPackage#getEnnumLiteral()
 * @model
 * @generated
 */
public interface EnnumLiteral extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.kulto.kultoDsl.KultoDslPackage#getEnnumLiteral_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.kulto.kultoDsl.EnnumLiteral#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Popis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Popis</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Popis</em>' containment reference.
   * @see #setPopis(Popis)
   * @see org.kulto.kultoDsl.KultoDslPackage#getEnnumLiteral_Popis()
   * @model containment="true"
   * @generated
   */
  Popis getPopis();

  /**
   * Sets the value of the '{@link org.kulto.kultoDsl.EnnumLiteral#getPopis <em>Popis</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Popis</em>' containment reference.
   * @see #getPopis()
   * @generated
   */
  void setPopis(Popis value);

} // EnnumLiteral
