/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.kulto.kultoDsl.Primitive#getJavaType <em>Java Type</em>}</li>
 * </ul>
 *
 * @see org.kulto.kultoDsl.KultoDslPackage#getPrimitive()
 * @model
 * @generated
 */
public interface Primitive extends Type
{
  /**
   * Returns the value of the '<em><b>Java Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Java Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java Type</em>' attribute.
   * @see #setJavaType(String)
   * @see org.kulto.kultoDsl.KultoDslPackage#getPrimitive_JavaType()
   * @model
   * @generated
   */
  String getJavaType();

  /**
   * Sets the value of the '{@link org.kulto.kultoDsl.Primitive#getJavaType <em>Java Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java Type</em>' attribute.
   * @see #getJavaType()
   * @generated
   */
  void setJavaType(String value);

} // Primitive
