/**
 * generated by Xtext 2.10.0
 */
package org.kulto.kultoDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.kulto.kultoDsl.KultoDslPackage#getType()
 * @model
 * @generated
 */
public interface Type extends RootElement
{
} // Type
