/*
 * generated by Xtext 2.10.0
 */
package org.kulto


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KultoDslStandaloneSetup extends KultoDslStandaloneSetupGenerated {

	def static void doSetup() {
		new KultoDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
