/**
 * generated by Xtext 2.10.0
 */
package org.kulto.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.kulto.ui.AbstractKultoDslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KultoDslUiModule extends AbstractKultoDslUiModule {
  public KultoDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
