/*
 * generated by Xtext 2.10.0
 */
package org.kulto.ui.tests;

import com.google.inject.Injector;
import kultodsl.ui.internal.KultodslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class KultoDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return KultodslActivator.getInstance().getInjector("org.kulto.KultoDsl");
	}

}
